version: "3.8"
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
